### ISSUE TITLE
New-index.js

### ISSUE THREAD

**Issue by FOR-Shu** [FCU-iOSClub/Website2022#30]
Context us.
Join us BTN.

**Comment by FOR-Shu** [comment]
在底部添加聯絡我們專區。
即在開頭文案添加按鈕。
廣告部分的更改。

**Comment by FOR-Shu** [comment]
@TonyPepeBear 我需要你的救助，我更新了首頁開頭那段的按鈕，但我做不出手機版的：（ I NEED YOUR HELP.

**Comment by TonyPepeBear** [comment]
![CleanShot 2022-05-26 at 15 54 41@2x](https://user-images.githubusercontent.com/41405045/170444100-d4b3617c-40a0-4748-8312-4e8c2985bcfd.jpg)

**Comment by FOR-Shu** [comment]
Great!
Excellent!

**Comment by TonyPepeBear** [comment]
merge to #33
